### ISSUE TITLE
autopilot package?

### ISSUE THREAD

**Issue by sneakers-the-rat** [jlesquembre/autopilot#13]
Hello! I'm working on putting a package on PyPI with the same name (https://github.com/wehr-lab/autopilot) and I'm wondering if you are still working on this, and if not if we can come to some sort of arrangement re: the name on PyPI? Let me know, if you'd like to speak further i can drop my email :)

**Comment by jlesquembre** [comment]
I want to keep the name. While I'm not working in this project, it currently works, and I still use it in some old projects.
