### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by kootenpv** [jlesquembre/autopilot#3]
I'm wondering how the versioning works of packages created?

It drives me crazy to have to update the version count, so I personally use a [deploy.py](https://github.com/kootenpv/yagmail/blob/master/deploy.py)

**Comment by jlesquembre** [comment]
I added a section to the docs to try to explain it:
http://autopilot-docs.readthedocs.org/en/latest/intro.html#version-handling

I hope now is clearer, let me know if not.

**Comment by kootenpv** [comment]
Clear. Only one more thing:

How to bump major/minor/bug fix?

`ap release -major / -minor / -bug` or something?

**Comment by jlesquembre** [comment]
Um, I need to think about it, but it makes sense to be able to provide it on the command line, that way probably more people will be aware of [Semantic Versioning](http://semver.org/)

**Comment by jlesquembre** [comment]
Added on version 0.3.0, see http://jlesquembre.github.io/autopilot/intro.html#command-line-options

**Comment by kootenpv** [comment]
Great.
